### PR TITLE
Fix broken Reports query

### PR DESCRIPTION
**Pull request by joecklau**
For commit https://github.com/Merchello/Merchello/pull/2193/commits/1ccc3f8d0acb71d5b0d0888dd19eea604fdecb05,

After upgrading to 2.7.0, In Backoffice's Report view, all report pages are broken. The reason is that "GetDateForSqlEndOfDay()" return Date string like "27 October, 2018 12:39:00.000" which is not a ISO date recognized by Azure SQL server / MSSQL, thus throwing exception. 

We should just pass the DateTime object, and trust the native DateTime object conversion instead.

### CODE REVIEW

**Comment by joecklau** [comment]
For commit https://github.com/Merchello/Merchello/pull/2193/commits/0826fc99a4d6187503c4a8a30014941b62bc1c5a,

This is a request to replace "internal" to "public" on models and methods, so that the community is much easier to extend Merchello.

In this commit, I pushed some of the necessary change for my case only, but I propose to give a global replace on "internal" by "public" actually.

What is my case? My case includes plugin for cloud environment support, custom report generation from the invoice/order/payment, extension for per-item shipping, etc.

**Comment by YodasMyDad** [comment]
Thanks for the PR. Always appreciated. I am using 2.7.0 on MSSQL and the reports are working fine? I'll pull this in anyway later and check they still work as expected.

**Comment by Vrijdagonline** [comment]
Is there a reason why this PR was not added to 2.7.1? After upgrading I have also that all Reports are broken.

`System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string.`

**Comment by YodasMyDad** [comment]
I need to look at the other files changed. Will edit and get into next release

**Comment by Vrijdagonline** [comment]
@YodasMyDad No worries buddy. I just merged these changes locally and can confirm that the reports started working again.

**Pull request merged**
