### PR TITLE
1.12.0

### PR DESCRIPTION
**Pull request by chris64digital**
I have created the notes functionality and related methods for orders. Also fixed a small typo!

### CODE REVIEW

**Comment by chris64digital** [comment]
Have found a couple of issues relating to moving this code up from 1.9.1 where I originally wrote it to 1.12.0

**Comment by chris64digital** [comment]
Notes now working against 1.12.0 branch

**Comment by rustyswayne** [comment]
@chris64digital did not have time to get this into 1.13.0.  Once I release, I'll review and get it into 1.13.1.

**Comment by rustyswayne** [comment]
@chris64digital I've been working on getting this merged into 1.13.1 and wanted to let you know I'm super impressed with how you've followed the existing patterns.  Very much appreciate that.  

I've changed the constructors in the NoteService to be Umbraco 7.3.0 compatible due to the ILogger breaking change.  

I'm also going to split out the Angular model builder into it's own factory file like all of the other ones are - but I do like having them in the same file as you've done so it's something to consider as we start looking at the Umbraco V8 back office refactoring and Angular 2.

Also, the changes to the SalesOverviewController / resource are being moved to the Merchello.Web.Ui.Client project so they don't get overridden with the grunt build.  

The last thing I'm going to add is a migration so that the database table is added in an upgrade and I'll also verify that the table is added during the installation process.  

Awesome Job and thank you very much!!!!

**Comment by rustyswayne** [comment]
@chris64digital is there a way to add notes from the back office?

**Comment by rustyswayne** [comment]
I merged this into 1.13.1 - thanks a ton!

**Pull request closed without merging**
