### PR TITLE
Fixes #2239 by abstracting PayPal out

### LINKED ISSUE #2239: Extrapolate payment providers into separate Nuget packages
Currently looking at updating the community-provided Stripe provider to support Merchello 2.0+, and Merchello.Core has a dependency on the PayPal SDK.

This seems... horrible.

Will open a fork & send in PRs.

### PR DESCRIPTION
**Pull request by jamiehowarth0**
And updates signatures for StringExtensions (internals that need to be shared are bad, have moved these to Umbraco StringExtensions calls instead, these will be addressed with NDepend later).
PR for Braintree & Authorize.Net to follow later. Suggest bringing in the community Stripe plugin later on too (due to new SCA requirements since last September).

### CODE REVIEW

**Comment by jamiehowarth0** [comment]
Latest Azure Devops test passes, the only issue is the AppVeyor build is broken. I'll dig into this tomorrow.

**Comment by jamiehowarth0** [comment]
I also took this chance to nuke out the NugetBackup directories that had been committed into the repo, as they shouldn't be needed at this juncture.

**Comment by YodasMyDad** [comment]
The AppVeyor build is linked to myget and creates a nuget package which I use for installing non releases on my own site and also for testing. Does this new Azure one do that?

**Comment by jamiehowarth0** [comment]
No, the Azure build is completely different to the AppVeyor one. I really think we should only have one  build environment rather than two, seems odd to have two separate ones.

**Comment by YodasMyDad** [comment]
Hmmm it was always only AppVeyor. I've just tried the AppVeyor build with a simple update and it fails. Something has changed on AppVeyor. I'll remove Azure for the moment

**Comment by jamiehowarth0** [comment]
Cool, I'll try using the AppVeyor build locally and see what's going on. I think it's Nuget restore causing some issues.

**Comment by YodasMyDad** [comment]
I#m mystified. I have no idea where that Azure build is coming from!! Or why AppVeyor has started failing!!

**Comment by YodasMyDad** [comment]
I can see you have added the Azure Merchello app some how.

https://benjaminhowarth.visualstudio.com/Merchello/_build/results?buildId=106&view=results

 Can you please delete that ASAP. I don't want that building my commits or the others. I want to stick with AppVeyor for now.

**Comment by jamiehowarth0** [comment]
Have done 👍🏻

**Comment by YodasMyDad** [comment]
Well I'm completely stumped with AppVeyor at the moment. It's just not building the projects? It was working fine last commit a couple of weeks ago and I haven't touched this or AppVeyor since!

**Comment by YodasMyDad** [comment]
What is weird is if I try and build a commit that previously built successfully in AppVeyor it now fails...

**Comment by jamiehowarth0** [comment]
I've worked it out. Nuget in VS2019 has used `<PackageReference>` instead of packages.config for Nuget packages. Fixing now...

**Comment by YodasMyDad** [comment]
Where is this?

**Comment by jamiehowarth0** [comment]
The separated payment provider project.

**Comment by YodasMyDad** [comment]
It can't be that. It's not building the main merchello-dev branch now, when all that's changed is a couple of lines in a class. And I tried triggering a rebuild of a commit in AppVeyor that had built successfully but now it fails.

**Comment by jamiehowarth0** [comment]
So, diagnosis so far:
AppVeyor fails (I think this is cause it's calling restore on the wrong solution file)
Local works with regular build.cmd with separated payment providers and correct packages.config refs.
I want to walk through what the AppVeyor build does in some detail, cause I think it can be simplified in some ways, plus we now need to produce Nuget packages for the payment providers.

**Comment by jamiehowarth0** [comment]
This can be merged as-is as it compiles & works, but I'm working on the nuspecs for the DLLs so that:

- [ ] FastTrack includes PayPal and Braintree providers, in both Nuget & Umbraco packages
- [ ] PayPal & Braintree packages are available as separate Nuget packages

**Comment by YodasMyDad** [comment]
I can't have this breaking AppVeyor. As I mentioned before I use the MyGet feed (In Azure pipelines) for a number of websites. So if we merge this, then the AppVeyor myget feed is broken and also I can't merge in the other small changes I'm making.

**Comment by YodasMyDad** [comment]
Actually the more I think about this, the more it's not a good idea. This is going to cause too many problems for a relatively stable project. If it ain't broke, don't fix it. I have a few projects which this will break and cause a fair bit of work including getting all the azure pipelines running again. 

I'm going to go back to my original plan and leave this project dormant. If you want to clone this and name it MerchelloV8 or whatever and carry it on, then I'm happy for you to do that. Then once you have a working code base and people can install your version. I'll then link from this project to yours to direct people to use that.

**Comment by TimGeyssens** [comment]
Hey why not have @benjaminhowarth1 have access to this repo and work on a new branch? That way folks now there is a new version in progress... and can still contribute...(if they want) since I think a fork is less findable and also doesn't give the same level of 'this is official' more like a personal playground... 
And with that new branch it won't affect your existing workflows... like appveyor /myget and all.. open source should applaud new contributors and taking over stalled projects... of course you still have ownership @YodasMyDad

**Comment by jamiehowarth0** [comment]
@YodasMyDad OK, I now have the AppVeyor build working locally with the buildscripts. Can we try and force a build on AppVeyor to see if this works?

**Comment by jamiehowarth0** [comment]
For anybody reading this, here are my personal & business plans for Merchello:

1. I'd love to see a release for V7 that extracts the separate payment providers out and still allows for bugfixes. It's a relatively simple process, with mostly namespace changes more than anything else, allows people to opt-out of payment gateways they don't want or need, and allows for additional extensibility (looking at Stripe and other payment providers/invoicing bolt-ons - e.g. I want to build a Quickbooks integration).
This is mostly because I have current V7 sites that require adding ecommerce functionality, and I was hoping to leave the options open, for those still building new sites on V7 (for stability & wide plugin support) to still have a robust ecommerce system available to them. I don't want to be forced to upgrade my projects to V8 just for Merchello, cause the plugins I'm using on them aren't V8-ready, and I think there's still some mileage to improve V7 of Merchello without straying too far into V8 rebuild territory. Whilst this PR looks large, mostly that's cause I deleted the NugetBackup directory in the FastTrack demo project.
2. After this, I'd like to start moving towards an Umbraco V8 release. Obviously, using the Merchello branding is entirely up to Lee, but I'd prefer not to hard-fork the project here. The Merchello brand is known, has presence, and I want to help take it forward, for myself and for the community.
3. Selling ad-hoc support packages for Merchello, should anybody want them.

That's my 2c.

**Comment by TimGeyssens** [comment]
@benjaminhowarth1 sounds like a decent plan :) @YodasMyDad what do you think? Benjaming can still work on a different branch so your flows don't get interrupted...

**Comment by dclinton182** [comment]
Be great if we can keep the V7 project going  we have a site that's using it which we are planning on launching when things have settled down so would be great to keep it available for future tweaks and changes!

**Comment by YodasMyDad** [comment]
> Be great if we can keep the V7 project going we have a site that's using it which we are planning on launching when things have settled down so would be great to keep it available for future tweaks and changes!

Firstly, this was always and is the case. I have been fixing and adding very minor things in the background for v7 Merchello for years. It was always going to be maintenance mode. You do all realise that official support for umbraco V7 will most probably stop end of next year. They are desperate for people to move to V8. So it doesn't make sense to continue to spend large amount of time on a v7 version of Merchello apart from fixing any minor bugs I find. 

> Hey why not have @benjaminhowarth1 have access to this repo and work on a new branch? That way folks now there is a new version in progress... and can still contribute...(if they want) since I think a fork is less findable and also doesn't give the same level of 'this is official' more like a personal playground... And with that new branch it won't affect your existing workflows... like appveyor /myget and all.. open source should applaud new contributors and taking over stalled projects... of course you still have ownership @YodasMyDad

I am happy to create a merchellov8 branch, and have that be the official v8 branch. But I am not having a stable v7 version or main branch stripped apart and added to. There is absolutely no need to refactor or split out the current payment providers. It's been fine for years and doesn't hinder anything anyone wants to do. 

You can still add your own payment providers. Yes the main project has references to paypal and braintree. But it's not been a problem in the entire lifetime of this project, there were at least 5 or 6 other payment provider plugins at the peak and it never hindered them. As I say. Lets not try and fix something that isn't broken. I've seen this tried many, many times, with bad consequences. 

> I'd love to see a release for V7 that extracts the separate payment providers out and still allows for bugfixes. It's a relatively simple process, with mostly namespace changes more than anything else, allows people to opt-out of payment gateways they don't want or need, and allows for additional extensibility (looking at Stripe and other payment providers/invoicing bolt-ons - e.g. I want to build a Quickbooks integration).

Again, there is just no need to do this. And what might be a relatively simple process will cause a lot of work and hassle elsewhere. So it's just not worth it. You can still create stripe and quickbooks plugins, I believe both of them were done at some point already. Just look at the bottom of this page

https://merchello.com/plugins/

> After this, I'd like to start moving towards an Umbraco V8 release. Obviously, using the Merchello branding is entirely up to Lee, but I'd prefer not to hard-fork the project here. The Merchello brand is known, has presence, and I want to help take it forward, for myself and for the community.

As I've said from the beginning. If you want to have a crack at a V8 version then I'm absolutely fine with that. However, it's a huge undertaking. Myself and Rusty were keeping an eye on the V8 branch while it was being developed and talking behind the scenes that we would need to rewrite a substantial amount of the project to get it to work. And decided not to take it further. One of the few big mistakes was tying this project too closely to Umbraco v7 itself. 

Just so we don't get further into a more discussions about v7 version. The v7 version of Merchello is staying in maintenance mode and I will not be stripping out the payment providers or making any large changes to the code base. I won't be discussing that side of it further. The v8 version, I'm happy if people want to have a crack at it.

**Comment by TimGeyssens** [comment]
@YodasMyDad thanks for the response :) yeah I agree that putting a lot of effort in the v7 version seems like lost hours... so maybe if that is @benjaminhowarth1 goal then a fork seems best... on the other hand if it is for porting to Umbraco v8 then a branch makes most sense like you say Lee... not that familiar with the codebase but what would be the greatest effort? I migrated a few packages (like UI-O-Matic) and that was ok...

**Comment by jamiehowarth0** [comment]
@TimGeyssens & @YodasMyDad you both make valid points re the v7 dev. In my view, payment providers should've been abstracted a long time ago out of core, and that's an architectural failing I'm trying to address now, so that a Merchello build feels "clean" even on V7 up to the end, whilst looking at longer-term options, but I get why it isn't hugely beneficial for you.
My perspective is it's righting a wrong that happened way back when, and doing so, for me, would help me mentally shape the architecture going forward. But my OCD can go overdrive sometimes 😂

Alright, so what I'll propose is this:

- [ ] Create a new merchello-dev-providerabstraction branch. This'll run parallel with @YodasMyDad's merchello-dev branch, & I'll merge that branch in regularly, thus keeping maintenance in sync, and act as a "springboard" into my v8 effort;
- [ ] Establish new CI/CD for my provider abstraction & v8 on Azure Devops;
- [ ] Create a v8-dev branch;
- [ ] Long-term, I'd like to implement Git flow so work happens on feature branches, merged into develop for Myget builds, and merged into master with tags for releases. That will involve some repo housekeeping later down the line.

How's this sound to everyone? Best of both worlds... I get to release a v7 product that I want to install on my sites (and maybe others do too, but it's a patched release). I get to determine the v8 direction & CI/CD setup, with a long-term view to tidying up the repo to support ongoing development.

I think this keeps everyone happy? V7 with abstracted providers (me + a few others), main V7 releases (Lee + also others), both kept in sync, V8 progress (ROW).
It also puts the onus on me to create a V7 package designed specifically for new installs, rather than breaking existing builds.

**Comment by jamiehowarth0** [comment]
So, with that in mind, I'll close this PR, and create a new one that scraps the NugetBackup directory anyway (cause that shouldn't be in there), without my provider work.

**Comment by TimGeyssens** [comment]
@benjaminhowarth1 think that is in line with what has been discussed, so go for it :) (@YodasMyDad if you are happy with it can you give Ben access?) , good luck! 🍀

**Comment by jamiehowarth0** [comment]
@TimGeyssens I already do as a maintainer, but thanks for the heads! #h5yr

**Pull request closed without merging**
