### PR TITLE
fix param limit when products have many options

### PR DESCRIPTION
**Pull request by cwjackso**
There is an issue with the 2100 parameter limit still in the latest code. The issue is fixed in this pull request by stopping building such a monstrous SQL statement :)

"ChunkSize" is a potential issue still as it is dependent in the total product options, I've set to 100 which works for us.

Thanks

### CODE REVIEW

**Comment by cwjackso** [comment]
Hi @rustyswayne , this causes an error when saving a product in the admin area so is definitely bug fix not enhancement.

Thanks

Carl

**Comment by cwjackso** [comment]
We were really hoping this would be in the latest Merchello release guys. Will you be releasing a patch at some point in the near future?

We have a live site with major issues with product saving because of the number of product options and were having to use a local built Merchello package on live.

Its actually part of a bigger issue where even with this fix the admin area is very slow once you add several options to a product. I can send a db over showing the issues if that's helpful?

Thanks

Carl

**Comment by YodasMyDad** [comment]
Why have you changed the 'chunk' size to just 100? It was set as 500 previously and I believe this is much better performance? I tested it locally, and didn't have any issues?

**Comment by YodasMyDad** [comment]
Sorry. Should have started with 'Thanks for taking the time to do a PR' 👍

**Comment by cwjackso** [comment]
The 500 Chunk size still caused issues for us from what I remember - this is why I added the constant value so I could easily change it until I found something which worked.

Have you recreated the issue before the PR? try making a  product with 6 shared options with the following config....

- option 1 (3 choices)
- option 2 (2 choices)
- option 3 (6 choices)
- option 4 (11 choices)
- option 5 (3 choices)
- option 6 (7 choices)

This generates 8316 variants and should error on save until you apply my PR.

Thanks

Carl

**Comment by YodasMyDad** [comment]
Actually. I don't know how you are getting the product to save with that many options. I am trying it locally with the exact same options with 100, 200 and 500 and it constantly fails. I haven't been able to get it to save once.

**Comment by YodasMyDad** [comment]
Actually. I just realised it's because I'm using SQLCE!! I'll test this with normal SQL. Merchello should not be run on SQLCE and we should not support it really.

**Comment by cwjackso** [comment]
Yeah it's sluggish with SQL server still!

The front end of the site is fine. We have something very custom for configuring products and the helper etc here is great.

Latest release is much better admin side and with a few more optimisations and fixing the product listing issue I raised I think it would be fine for us.

Thanks for looking into it

Carl.

**Comment by YodasMyDad** [comment]
I have pulled this in, but the changes have not made any performance improvement my end no matter what I put the chunk size to. There was an error with the SQL limit I found during testing but it was not addressed in this PR but I have used a chunk size variable you added. I am going to mark this as complete for now (And open another issue for speed/query performance), although I didn't pull in the changes I really appreciate you taking the time to do a PR and hope for lots more in the future 👍

**Pull request closed without merging**
