### PR TITLE
FastTrack - add forgot password and change password functionality

### PR DESCRIPTION
**Pull request by trevorloader**
Just thought I'd include a bit more functionality that people might require for FastTrack.

I've updated the FastTrack installer to create the content nodes but it seems like I'm missing something.  I can't figure out where/how the document types and templates are created?

Do you include these as files in the package build and they install without you having to do anything?

If so, you'll need to duplicate the ftLogin document type can create a ftChangePassword and ftForgotPassword ones.  Note too that ftAccount needs to have ftChangePassword as an allowed child as change password needs to sit at /account/change-password/ in order to protect it (be secure).

Upshot - I haven't tested the fasttrack installer.

### CODE REVIEW

**Comment by rustyswayne** [comment]
The FastTrack package is just created through the back office - so if you added a document type / template they need to be selected in the create package manager.  I've just released version 2.2.0 and will be merging the mdev-230 branch into merchello-dev shortly.  

Once this is done, can you update your local to make sure there are no merge conflicts?

After that, I'll pull from your branch (locally) and check things out to give you a hand =)

**Comment by trevorloader** [comment]
Will do.

**Comment by rustyswayne** [comment]
Hey Trevor - can you add an issue in the issue tracker so I can get this one scheduled to merge in.  We have a training coming up in the UK that pretty set in stone w/respect to the manual =)

**Comment by trevorloader** [comment]
Will do.  I'll create the issue and send new PR in the next couple of days.

**Pull request closed without merging**
