### PR TITLE
Added more missing keys and  adding Dutch translations

### PR DESCRIPTION
**Pull request by ghost**
This PR is still WIP.

1. The other PR #2123 is obsolete and can be closed

2. Need opinion from @YodasMyDad or @rustyswayne  regarding code style for localisation the notificationmessages.

option 1: 
`					localizationService.localize("merchelloNotification_productSaved").then(function(value){
						notificationsService.success(value);
					});`

option 2: `notificationsService.success(localizationService.localize("merchelloNotification_productSaved"))`

Which approach do you guys think is best?

Cheers guys,
Arjan Woldring

### CODE REVIEW

**Comment by Vrijdagonline** [comment]
@YodasMyDad Mind you take a look at my question? 

Would be great, because with the notificationmessages localized, everything is then done except the marketing coupon conditions/restrictions and some stuff in the Gateway Providers tree.
But all in all, for the editors, managing products and such, is nearly everything localized. So would be awesome to have the final push for notification messages localized. 

Cheers,
Arjan

**Comment by Vrijdagonline** [comment]
@YodasMyDad  or @rustyswayne ? Any suggestions so I can wrap this all up.

**Comment by Vrijdagonline** [comment]
@YodasMyDad Can you merge this PR too? Last week you merged #2123 which my PR already had fixed with more consisted naming. Personally I would revert #2123 and apply this PR.

This PR fixes almost all of the localizationissues.

Cheers Arjan

**Comment by YodasMyDad** [comment]
Yes, I am going to merge. I merged another that has conflicts with this.

**Comment by Vrijdagonline** [comment]
@YodasMyDad awesome job bud! You are on a roll! Good to see that you have found some time to give some love to merchello.

Thank you.

**Pull request merged**
