### PR TITLE
M-979 Taxation rounding issue when "Include in product pricing"

### PR DESCRIPTION
**Pull request by trevorloader**

### CODE REVIEW

**Comment by rustyswayne** [comment]
Looks great - I'll test and merge tomorrow.  I had never seen CultureInfo.InvariantCulture.NumberFormat.CurrencyDecimalDigits before ... that's sweet!

**Comment by trevorloader** [comment]
CultureInfo.InvariantCulture.NumberFormat.CurrencyDecimalDigits will always be 2dp - so still not "right".  What would be better is if that was the actual culture (if you can get it there?)...so for 3dp cultures/currencies, it would round to an appropriate dp.  Doable?

**Comment by rustyswayne** [comment]
Unfortunately everything is based off the country code used by addresses.  

There is a currency format in store settings that can be configured via the merchello.config by currency code.  Have you seen the extensions in the Bazaar?  

https://github.com/Merchello/Merchello/blob/merchello-dev/src/Merchello.Bazaar/ModelExtensions.cs#L19

I'm hesitant to break into the class and force in a new setting - I think that would be better done with some sort of external helper that could be used everywhere.

Can you give the extensions a look - maybe we could back something like this into the core?

**Comment by trevorloader** [comment]
The easiest and most obvious place for the enhancement would be to /src/Merchello.Core/FormattingExtensions.cs ... following the same pattern as the current FormatAsStoreDate.  Eg add another one as FormatAsStoreCurrency that looks at the store currency and formats as the appropriate decimal places.

Or I can look at a whole new class.

Which would you prefer?

**Comment by rustyswayne** [comment]
Hey Trevor,

I've been thinking about this and am leaning towards a static class - something like this:

https://gist.github.com/rustyswayne/52a9b7316984ff1ef5c4b546c83f0949

We would have to add an event handler list:

             // Merchello
            StoreSettingService.Saved += StoreSettingServiceOnSaved;

Which would 

                   /// <summary>
        /// Resets the store currency.
        /// </summary>
        /// <param name="sender">
        /// The sender.
        /// </param>
        /// <param name="e">
        /// The save event args.
        /// </param>
        private void StoreSettingServiceOnSaved(IStoreSettingService sender, SaveEventArgs<IStoreSetting> e)
        {
           CurrencyContext.ResetCurrency();
        }

What do you think?

**Comment by trevorloader** [comment]
Yes I'm happy either way....although your example class doesn't address the original issue which is to round an amount to the decimal places of the currency...returning a decimal not a formatted string.

Eg, add another function to your class called RoundCurrency

public static decimal RoundCurrency(decimal amount)
{
    return System.Math.Round(amount, new CultureInfo(currencyCode.Value, false).NumberFormat.CurrencyDecimalDigits);
}

The only thing the above needs is the store currency code (eg NZD) to get the culture and then get the currency decimal places.

Then is can be used in the taxation code) to fix the rounding issue:

var priceCalc = (product.Price * taxRate).RoundCurrency();

**Comment by rustyswayne** [comment]
I think it makes sense to add that as a static method to the context, but there will need to be some error checking as not all currency codes will match the culture info reference (like Cyprus)

**Comment by rustyswayne** [comment]
Hey Trevor,

I've added the CurrencyContext to Merchello.Core (knowing it does not address this issue entirely) but I think it is a better place to start.  

I've been working on the PayPal Express Checkout provider and interestingly internally they require the same thing, except,  0, 2, or 3 decimal points and it got me thinking that we could look at the ICurrencyFormat interface in the Core and work our way up from there.  That is already wired into the CurrencyContext ...  have a look and let me know what you think.

I'm going to close this PR for house keeping, but I'd like to get the issue sorted.

**Comment by trevorloader** [comment]
Great, will have a look. Thanks Rusty.

**Pull request closed without merging**
