### PR TITLE
Fix for Issue/m 682

### PR DESCRIPTION
**Pull request by ProNotion**
Extends the [merchAppliedPayment].[description] database field to 500 characters

### CODE REVIEW

**Comment by rustyswayne** [comment]
@ProNotion many thanks!  I'll pull this into a local branch and merge it into the 2.3.0 stuff this week sometime.  Great work!

**Comment by rustyswayne** [comment]
@ProNotion This worked great.  I did go ahead and move the SQL call to check the column size into an internal DatabaseExtensions class - it made since to do it now since I also wanted to do the same (secondary) check before actually executing the migration in case one of the other migrations failed during the 2.3.0 upgrade and it had to be run again.  No sense in updating it if it has already been changed.

Really appreciate the work!!!

**Comment by rustyswayne** [comment]
@ProNotion Caught one thing after the merge - just FYI.  So that on new installs then field is installed with a length of 500.  Just need to add the Length attribute to the AppliedPaymentDto
https://github.com/Merchello/Merchello/blob/merchello-dev/src/Merchello.Core/Models/Rdbms/AppliedPaymentDto.cs#L48

**Comment by ProNotion** [comment]
Good catch, sorry about that. Hopefully the first of many more contributions :)

**Pull request merged**
