### PR TITLE
Localize missing Keys and added Dutch

### PR DESCRIPTION
**Pull request by ghost**
Localization for property editor "Collection picker".

### CODE REVIEW

**Comment by Vrijdagonline** [comment]
Added Localize a few in the Sales -> Payments tab

**Comment by Vrijdagonline** [comment]
Hello @YodasMyDad ,

I need your help! :) 

Do you have a suggestion for translating the Coupon/Offer Components? It is declared as a class attribute in c#.

Like here: [https://github.com/Merchello/Merchello/blob/merchello-dev/src/Merchello.Web/Discounts/Coupons/Rewards/CouponDiscountLineItemReward.cs#L17](https://github.com/Merchello/Merchello/blob/merchello-dev/src/Merchello.Web/Discounts/Coupons/Rewards/CouponDiscountLineItemReward.cs#L17)   

Would love your feedback on how to tackle this!

Awesome job guys!
Cheers bud!
Arjan Woldring

**Comment by Vrijdagonline** [comment]
First commit for the Coupon. More will follow.

**Comment by Vrijdagonline** [comment]
@YodasMyDad  and @rustyswayne 
This Pull Request can be merged for now. Later on I'll do a PR for localizing Notifications and Coupon/Offers.

**Comment by Vrijdagonline** [comment]
Would love to have this merged. I have a new branch with some css-style changes. But this PR is from master branch so I can't easily do a new PR with the css styles because it's based on my master branch with all the localization fixes.

**Comment by YodasMyDad** [comment]
Merged 👍  Keep up the great up work.

**Comment by Vrijdagonline** [comment]
Thanks Lee! Awesome job!

**Pull request merged**
