### PR TITLE
Latest version of PayPal provider (including all changes of Flavio Spezi)

### PR DESCRIPTION
**Pull request by KonstKhrist**
Signed-off-by: Konstantin <konstantin@scandiaconsulting.com>

### CODE REVIEW

**Comment by fspezi** [comment]
Hi KonstKhrist, I look that you have create new Pull Request for PayPal Provider.

You have generate a new Pull Request from my work (thanks!). Unfortunatelly I need to alert you that this code contains an invalid settings parameter.  
I had speak with Rusty Swayne; look this: http://our.umbraco.org/projects/collaboration/merchello/merchello/60524-How-to-use-GatewayProviderServiceApplyPaymentToInvoice-method

As you can read, the "Capture funds?" parameter is to remove because the payment gateway interface integrates this feature through `PerformAuthorizePayment` and `PerformAuthorizeCapturePayment`.

Can you fix it?

**Comment by KonstKhrist** [comment]
OK, I'll fix it on weekend. Thanks!

**Comment by KonstKhrist** [comment]
Fixed

**Comment by KonstKhrist** [comment]
It's defined in PayPalPaymentGatewayMethod.cs:30
protected override IPaymentResult PerformAuthorizeCapturePayment(IInvoice invoice, decimal amount, ProcessorArgumentCollection args)
{
return InitializePayment(invoice, args, amount);
}

**Comment by fspezi** [comment]
I am not secure that it is done: PerformAuthorizeCapturePayment will be "authorize then capture" the payment on PayPal account. Are you secure that this code do it?

**Comment by fspezi** [comment]
**Other argument**:  
I look that our gateway configuration UI does not works with newes Merchello release (1.7.0). Then I fix it. This is the entire "merchello.paypal.controller.js" file:

(function (controllers, undefined) {

    /**
     * @ngdoc controller
     * @name Merchello.Dashboards.Settings.Shipping.Dialogs.ShippingMethodController
     * @function
     * 
     * @description
     * The controller for the adding / editing shipping methods on the Shipping page
     */
    controllers.PayPalGatewayProviderController = function ($scope) {

        /**
        * @ngdoc method 
        * @name init
        * @function
        * 
        * @description
        * Method called on intial page load.  Loads in data from server and sets up scope.
        */
        $scope.init = function () {

            //$scope.dialogData.provider.extendedData

            // on initial load extendedData will be empty but we need to populate with key values
            // 
        	var settingsString = $scope.getDialogDataSettings();
            $scope.paypalSettings = JSON.parse(settingsString);


            // Watch with object equality to convert back to a string for the submit() call on the Save button
            $scope.$watch(function () {
                return $scope.paypalSettings;
            }, function (newValue, oldValue) {
            	$scope.setDialogDataSettings(angular.toJson(newValue));
            }, true);
        };

        $scope.getDialogDataSettings = function () {
	    	var item = $scope.getDialogDataSettingsExtendedDataItem();
		    return item.value;
	    };

	    $scope.setDialogDataSettings = function (newValue) {
	    	var item = $scope.getDialogDataSettingsExtendedDataItem();
	    	return item.value = newValue;
	    };

	    $scope.getDialogDataSettingsExtendedDataItem = function() {
	    	for (var i = 0; i < $scope.dialogData.provider.extendedData.items.length; i++) {
			    var item = $scope.dialogData.provider.extendedData.items[i];
			    if (item.key == "paypalProcessorSettings") return item;
		    }
		    return null;
	    };

        $scope.init();
    };

    angular.module("umbraco").controller("Merchello.Plugin.GatewayProviders.Payments.Dialogs.PayPalGatewayProviderController", ['$scope', merchello.Controllers.PayPalGatewayProviderController]);


}(window.merchello.Controllers = window.merchello.Controllers || {}));

Can you merge this to your gateway version, please?

**Pull request merged**
