### PR TITLE
Stripe dialog controller bugfix

### PR DESCRIPTION
**Pull request by tigreye007**
It appears that the extendedData scope/structure has had some updates since this plugin was written.

### CODE REVIEW

**Comment by alindgren** [comment]
@rustyswayne - I'd like to accept this request and then migrate the project to https://github.com/alindgren/MerchelloStripeProvider, test it and release on our.

**Comment by rustyswayne** [comment]
Sounds great - just to confirm, you'd like me to merge it before ...


Rusty


-------- Original message --------

**Comment by tigreye007** [comment]
@rustyswayne FYI:  I only intended to include the stripe commit as part of this pull request.  It seems my performance updates in my fork automatically got included as well, and probably should NOT be directly merged in.

**Comment by alindgren** [comment]
@tigreye007, it appears there is only one file changed for the Stripe provider. If that's not dependent on the other changes, I can just manually include that in a new build at https://github.com/alindgren/MerchelloStripeProvider. Is that okay?

**Comment by tigreye007** [comment]
@alindgren Sounds good.

**Comment by rustyswayne** [comment]
@tigreye007 @alindgren I think doing the pull to Alex's repo is going to be the best at this point.  I can merge this in at the moment due to the unit of work refactoring.  Love the work, but we'll have to look at this in more detail when we start looking at a 2.0.0 version.

**Pull request closed without merging**
