### PR TITLE
M-825 Currency symbol formats

### PR DESCRIPTION
**Pull request by robgha01**
Added the functionality to configure currency formats based on currency
code.

### CODE REVIEW

**Comment by rustyswayne** [comment]
Thanks and awesome job.  I made a couple of tweaks so that default format was always returned from the service call.  Also, we cannot have a static method on the service, so I used the MerchelloContent singleton in the ModelExtensions.

Again great contribution!

**Comment by robgha01** [comment]
Thancks it looks good :)

**Comment by rustyswayne** [comment]
Hey Bud - I'm hoping to use your effort as an example of a community contribution at CG this year but want to give you credit.  Can you send me a DM on twitter (@rustyswayne) - I'd like to give you kudo's by name if you would not mind =)

**Comment by robgha01** [comment]
@rustyswayne ok

**Comment by robgha01** [comment]
@rustyswayne i tryed to send dide not work anyway my twitter is @RobertGhafoor i have ben in hospital for some time but im out recovering at home :)

**Pull request merged**
